package com.cloudbase.model;

public enum AuditAction {
    PROJECT_CREATED,
    SERVICE_CREATED,
    SERVICE_DEPLOYED,
    SERVICE_STOPPED,
    SERVICE_DELETED,
    DEPLOY_ACCESS_ENABLED,
    DEPLOY_ACCESS_DISABLED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_SUSPENDED,
    PASSWORD_RESET_SENT,
    ROLE_CHANGED,
    HOSTING_SETTINGS_UPDATED
}
